- name: Download RHEL ISOs
  hosts: localhost
  vars_files:
    - lab_vars.yml
  tasks:
    - ansible.builtin.include_role:
        name: package-downloader
      vars:
        rh_product_filename: "{{ item.filename }}"
        rh_product_checksum: "{{ item.checksum }}"
        rh_api_offline_token: "{{ offline_token }}"
      loop:
        - filename: rhel8.iso
          checksum: "{{ checksum.rhel8 }}"
        - filename: rhel9.iso
          checksum: "{{ checksum.rhel9 }}"
      when: offline_token is defined and offline_token != ""

- name: This play provisions VMs for Satellite demos
  hosts: localhost
  become: true
  vars_files:
    - lab_vars.yml  
  tasks:
    - name: Ensure required packages are in place
      ansible.builtin.yum: 
        name: "{{ packages }}"

    - name: Ensure libvirtd is running
      ansible.builtin.service: 
        name: libvirtd
        state: started
        enabled: true

    - name: Ensure libvirt can use root as user
      ansible.builtin.replace:
        path: /etc/libvirt/qemu.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.line }}"
      loop:
        - regexp: '#user = "root"'
          line: 'user = "root"'
        - regexp: '#group = "root"'
          line: 'group = "root"'

    - name: Restart libvirtd service
      ansible.builtin.service: 
        name: libvirtd
        state: restarted
   
    - name: Create required folders
      ansible.builtin.file:
        state: directory
        path: "{{ playbook_dir }}/terraform/kickstart/{{ item.instance }}"
        recurse: true
      loop: "{{ modules }}"

    - name: Create symbolic link to RHEL image
      ansible.builtin.file:
        src: "{{ playbook_dir }}/{{ item.version }}.iso"
        dest: "{{ playbook_dir }}/terraform/modules/{{ item.module }}/{{ item.instance }}.iso"
        state: link
      loop: "{{ modules }}"
          
    - name: Create a 1Mib file to store kickstart 
      community.general.filesize:
        path: "{{ playbook_dir }}/terraform/modules/{{ item.module }}/{{ item.instance }}-oemdrv.img"
        size: 1MiB
      loop: "{{ modules }}"
                         
    - name: Generate kickstart from template
      ansible.builtin.template:
        src: ks.cfg.j2
        dest: "{{ playbook_dir }}/terraform/kickstart/{{ item.instance }}/ks.cfg"
      loop: "{{ modules }}"
      vars:
        hostname: "{{ item.hostname }}"
          
    - name: Rebuild Kickstart config
      community.general.filesystem:
        fstype: ext2
        dev: "{{ playbook_dir }}/terraform/modules/{{ item.module }}/{{ item.instance }}-oemdrv.img"
        opts: -d {{ playbook_dir }}/terraform/kickstart/{{ item.instance }} -L OEMDRV
        force: true
      loop: "{{ modules }}"

    - name: Provision all terraform resources
      community.general.terraform:
        project_path: "terraform/"
        force_init: true
        variables:
          network_cidr: ' ["{{ network_cidr }}"]'
        state: present

    - name: Ensure required NM directories exist
      ansible.builtin.file:
        path: /etc/NetworkManager/{{ item }}
        state: directory
      loop: 
        - dnsmasq.d
        - conf.d      

    - name: Add Local resolver for the domain
      ansible.builtin.copy:
        content: server=/satellitedemo.labs/{{ network_cidr | next_nth_usable(1)}}
        dest: /etc/NetworkManager/dnsmasq.d/satellitedemo.conf

    - name: Configure NetworkManager for local DNS
      ansible.builtin.blockinfile:
        path: /etc/NetworkManager/conf.d/satellite-localdns.conf
        block: |
          [main]
          dns=dnsmasq
        create: true

    - name: Restart NetworkManager to reload config
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

    - name: Add servers to inventory
      ansible.builtin.add_host:
        hostname: "{{ item }}.{{ domain }}"
        ansible_user: root
        ansible_ssh_pass: redhat
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        groups:
          - "servers"
      loop:
        - el8-server
        - el9-server

    - name: Ensure to clean known_hosts
      ansible.builtin.known_hosts:
        host: "{{ item }}.{{ domain }}"
        path: ~/.ssh/known_hosts
        state: absent
      loop: 
        - satellite
        - el8-server
        - el9-server      
      become: false

- name: Check connection to servers
  hosts: servers,satellite
  gather_facts: no
  tasks:
    - name: Waiting for installation to end, it can take time!
      ansible.builtin.wait_for_connection:
        timeout: 1800
        sleep: 120

    - ansible.builtin.ping:

    - name: Setup is ready
      ansible.builtin.debug:
        msg: "Setup completed, now you can proceed with post install steps"

