---
- name: Satellite server configuration playbook
  hosts: satellite
  become: true
  vars_files:
    - lab_vars.yml
  tasks:
    - name: Register system with Red Hat Subscription Manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ rhsm_pool_id }}"

    - name: Disable all RHSM repositories
      community.general.rhsm_repository:
        name: '*'
        state: disabled

    - name: Enable required RHSM repositories
      community.general.rhsm_repository:
        name:
          - rhel-8-for-x86_64-baseos-rpms
          - rhel-8-for-x86_64-appstream-rpms
          - satellite-6.11-for-rhel-8-x86_64-rpms
          - satellite-maintenance-6.11-for-rhel-8-x86_64-rpms
        state: enabled

    - name: Ensure all packages are updated
      ansible.builtin.yum:
        name: '*'
        state: latest # noqa package-latest

    - name: Enable satellite module
      ansible.builtin.command: "dnf -y module enable satellite:el8"

    - name: Install satellite packages
      ansible.builtin.yum:
        name:
          - satellite
          - chrony
          - sos
        state: latest # noqa package-latest

    - name: Ensure chrony is enabled
      ansible.builtin.service:
        name: chronyd
        enabled: true
        state: started

    - name: Ensure firewalld is enabled
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Allow ports for satellite zone
      ansible.posix.firewalld:
        zone: public
        state: enabled
        permanent: true
        port: "{{ item }}"
      loop:
        - 80/tcp
        - 443/tcp
        - 5647/tcp
        - 8000/tcp
        - 8140/tcp
        - 9090/tcp
        - 53/udp
        - 53/tcp
        - 67/udp
        - 69/udp

    - name: Reload firewalld service
      ansible.builtin.service:
        name: firewalld
        state: restarted


    - name: Install satellite
      ansible.builtin.shell: |
        satellite-installer --scenario satellite \
        --foreman-initial-organization "Red Hat" \
        --foreman-initial-location "Raleigh" \
        --foreman-initial-admin-username admin \
        --foreman-initial-admin-password redhat \
        --enable-foreman-plugin-rh-cloud \
        --foreman-proxy-plugin-remote-execution-ssh-install-key true

    - name: Reboot server
      ansible.builtin.reboot:
