packages:
  - python3-lxml
  - python3-netaddr
  - python3-libvirt
  - python3-pip
  - libvirt-devel
  - libvirt
  - qemu-kvm
  - virt-install
  - virt-manager
modules:
  - module: 01_satellite_instance
    instance: rhel8-satellite
    hostname: satellite
    version: rhel8
  - module: 02_client_instance
    instance: rhel8
    hostname: el8-server    
    version: rhel8
  - module: 02_client_instance
    instance: rhel9
    hostname: el9-server
    version: rhel9
domain: satellitedemo.labs
checksum:
  rhel9: a387f3230acf87ee38707ee90d3c88f44d7bf579e6325492f562f0f1f9449e89
  rhel8: 8cb0dfacc94b789933253d5583a2fb7afce26d38d75be7c204975fe20b7bdf71
